version: "3.7"
services: 
        sql-server-db:
                container_name: "kpz-restaurant-db"
                image: mcr.microsoft.com/mssql/server:2019-latest
                ports:
                        - "1433:1433"
                environment:
                        SA_PASSWORD: "kpz-restaurant-passw0rd"
                        ACCEPT_EULA: "Y"